<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-07T23:51:25 BDT" name="Default suite" finished-at="2024-01-07T23:55:24 BDT" duration-ms="238965">
    <groups>
    </groups>
    <test started-at="2024-01-07T23:51:25 BDT" name="Default test" finished-at="2024-01-07T23:55:24 BDT" duration-ms="238965">
      <class name="resumeAnalyzer.testcases.PaymentTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:resumeAnalyzer.testcases.PaymentTest@515c6049]" started-at="2024-01-07T23:51:25 BDT" name="setup" finished-at="2024-01-07T23:52:13 BDT" duration-ms="47987" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Payment()[pri:1, instance:resumeAnalyzer.testcases.PaymentTest@515c6049]" started-at="2024-01-07T23:52:13 BDT" name="Payment" finished-at="2024-01-07T23:54:46 BDT" duration-ms="152779" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Payment -->
        <test-method signature="CustomerServiceDashboard()[pri:2, instance:resumeAnalyzer.testcases.PaymentTest@515c6049]" started-at="2024-01-07T23:54:46 BDT" name="CustomerServiceDashboard" finished-at="2024-01-07T23:55:16 BDT" duration-ms="30081" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[message success is not displayed in the search results expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: message success is not displayed in the search results expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at resumeAnalyzer.testcases.PaymentTest.CustomerServiceDashboard(PaymentTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CustomerServiceDashboard -->
        <test-method signature="messageHistoryTest()[pri:3, instance:resumeAnalyzer.testcases.PaymentTest@515c6049]" started-at="2024-01-07T23:55:16 BDT" name="messageHistoryTest" finished-at="2024-01-07T23:55:24 BDT" duration-ms="8065" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- messageHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:resumeAnalyzer.testcases.PaymentTest@515c6049]" started-at="2024-01-07T23:55:24 BDT" name="tearDown" finished-at="2024-01-07T23:55:24 BDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- resumeAnalyzer.testcases.PaymentTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
